server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-company-gateway-v1
    cloud:
      gateway:
        routes:
          - id: user-company-web-v1
            uri: lb://user-company-web-v1
            predicates:
              - Path=/users/**, /companies/**, /members/**
#  cloud:
#    gateway:
#      routes:
#        - id: web-v1
#          uri: lb://user-company-web-v1
#          predicates:
#            - Path=/api/web/**
#          filters:
#            - StripPrefix=2
